version: "3.2"
services:
  datascience:
    build: .
    image: youodf/datascience
    ports:
      - "8890:8888"
    volumes:
     - ./notebook:/app/notebook
     - ./src:/app/src
     - ./example:/app/example
    command: jupyter notebook --ip='0.0.0.0' --allow-root --no-browser
