version: "3.2"
services:
  kaggle-python:
    build: .
    image: youodf/kaggle-python
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - PROJECT_DIR=/app
    volumes:
      - .:/app
    command: jupyter lab --ip 0.0.0.0 --no-browser --allow-root